<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.375
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Empresas Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'email' => array(
		'from' => 'arkieta@hotmail.com',
		'to' => 'arkieta@hotmail.com'
	),
	'fields' => array(
		'custom_U827' => array(
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nombre\' is required.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U850' => array(
			'type' => 'string',
			'label' => 'Compañia',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Compañia\' is required.'
			)
		),
		'custom_U846' => array(
			'type' => 'string',
			'label' => 'Dirección',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Dirección\' is required.'
			)
		),
		'custom_U862' => array(
			'type' => 'string',
			'label' => 'Teléfono',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Teléfono\' is required.'
			)
		),
		'custom_U854' => array(
			'type' => 'string',
			'label' => 'Numero de empleados',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Numero de empleados\' is required.'
			)
		),
		'custom_U858' => array(
			'type' => 'string',
			'label' => 'Asunto',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Asunto\' is required.'
			)
		),
		'custom_U831' => array(
			'type' => 'string',
			'label' => 'Mensaje',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Mensaje\' is required.'
			)
		)
	)
);

process_form($form);
?>
